### PR TITLE
Eelektross patch 2

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Review by DeathlyPlays — COMMENTED** [review]
Tbh if you remove Dazzling for this it should be fine, since without Dazzling it'll have a form of counter :p

**Comment by ghost** [comment]
But then its ability wouldn't be as good

**Comment by ghost** [comment]
It still gets countered by vivid is a god and BAMD

**Comment by ghost** [comment]
Ill make it 1.25 if new need a nerf

**Comment by ghost** [comment]
Merging

**Pull request merged**
