### PR TITLE
Stellations new staffmon and add mystifi to the credits

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by DeathlyPlays** [comment]
Now you understand the pain that is Travis CI

**Comment by ghost** [comment]
Aight! Everything is good!

**Comment by ghost** [comment]
Merging

**Comment by ghost** [comment]
Rip I can't do it, just merge as is, I added mystifi to the credits list

**Comment by ghost** [comment]
Just a note, make sure to squash and merge it so it'll show up under 1 commit. Since there are so many edits and revisions.

**Comment by DeathlyPlays** [comment]
Didnt give me a notice to do it e.e

**Pull request merged**
