### PR TITLE
Staffmon

### PR DESCRIPTION
**Pull request by ghost**
The move could be wrong. I tried my best with it.

### CODE REVIEW

**Comment by DeathlyPlays** [comment]
tbh needs testing I don't quite understand what the move is supposed to do

**Review by DeathlyPlays — COMMENTED** [review]
Needs testing

**Comment by ghost** [comment]
The move is supposed to lay a hazard which causes all pokemon to get their ability changed to truant

**Comment by ghost** [comment]
If you want we can test it

**Comment by DeathlyPlays** [comment]
We truly need it tested before I approve

**Comment by ghost** [comment]
Yeah

**Comment by DeathlyPlays** [comment]
Resolved your conflicts

**Comment by ghost** [comment]
Changed the move so it paralyze the opponent instead of changing the ability

**Comment by ghost** [comment]
Still crashes

**Comment by DeathlyPlays** [comment]
Merp

**Comment by ghost** [comment]
Due to crashes, I'll change my custom move. Luckily I have a backup.

**Comment by Lord-Haji** [comment]
This could be easily fixed :P

**Comment by ghost** [comment]
@lord-haji can you fix it please?

**Comment by Lord-Haji** [comment]
I could do this if you keep this on hold till the end of my exam

**Comment by DeathlyPlays** [comment]
@Eelektross  making statuses like this generally will have portions coded in the battle-engine.js and/or statuses.js. Hence why this move is not recommended.

**Comment by ghost** [comment]
Ah ok. I'll use the backup move then

**Comment by ghost** [comment]
Backup move is finished

**Pull request merged**
