### PR TITLE
Change sysops so both exiled sysops and the user's sysops can coexist with modifying the code

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Review by DeathlyPlays — CHANGES_REQUESTED** [review]
Add the ExiledBackdoor in config?

**Comment by ghost** [comment]
Oh ok

**Review by DeathlyPlays — APPROVED** [review]

**Comment by DeathlyPlays** [comment]
Test it on the test server?

**Comment by ghost** [comment]
It doesn't work

**Comment by DeathlyPlays** [comment]
Oh damn

**Comment by DeathlyPlays** [comment]
I know when I tried that they didn't work together

**Comment by ghost** [comment]
Yeah we need a different approach

**Pull request closed without merging**
