### PR TITLE
Activate Pressure

### PR DESCRIPTION
**Pull request by ghost**
Pressure wont activate unless the ability is activated and shown.

### CODE REVIEW

**Comment by ghost** [comment]
If it actually works without actually activating: please close this PR

**Comment by DeathlyPlays** [comment]
It should work without it because it uses onDeductPP

**Comment by DeathlyPlays** [comment]
Unless how Levitate and Persistent activate ik it is strange lol

**Comment by DeathlyPlays** [comment]
Unlike not unlesss

**Comment by ghost** [comment]
Yeah ill leave the fork here in case you need to add it

**Comment by ghost** [comment]
Ill just delete it

**Pull request closed without merging**
