### PR TITLE
Patch 6

### PR DESCRIPTION
**Pull request by ghost**
added c7's ability and mon so far

### CODE REVIEW

**Review by DeathlyPlays — COMMENTED** [review]
On mods/essb/abilities.js Line 247 is indented incorrectly.  Line  270 needs to be tabbed once other than that looks good.

**Comment by ghost** [comment]
FUUUUUUUU- Err... Ill fix that :p

**Comment by DeathlyPlays** [comment]
You were missing some Prankster code haha I added it dw looks good now

**Comment by ghost** [comment]
Great

**Pull request merged**
