### PR TITLE
Patch 8

### PR DESCRIPTION
**Pull request by ghost**
Adding sketch mix and mega

### CODE REVIEW

**Comment by ghost** [comment]
Only 2 things wrong...

`/home/travis/build/DeathlyPlays/Exiled/mods/sketchmnm/items.js
  8:29  error  Parsing error: Unexpected token ;`

`/home/travis/build/DeathlyPlays/Exiled/mods/sketchmnm/scripts.js
  18:59  error  Parsing error: Unexpected token ;`

**Comment by Stellation** [comment]
`a`

**Comment by DeathlyPlays** [comment]
I'll fix em up

**Comment by DeathlyPlays** [comment]
The errors iirc are from the other files e.e

**Comment by ghost** [comment]
Oh ok thanks

**Pull request merged**
