### PR TITLE
Optimize Icon.js

### PR DESCRIPTION
**Pull request by AllianceSky-PS**

### CODE REVIEW

**Comment by Lord-Haji** [comment]
@AllianceSky-PS  Please make me understand in what ways ur making it better?
My code will check for every room and add to css everytime generateCSS() is ran. Like even if a new room is created after adding the icon it'll work.
Also u cannot add ur credits for a piece of wrong code

I needed to comment since I was involved

**Comment by AllianceSky-PS** [comment]
@Lord-Haji okay, i'll remove my credits. It works almost same as your code but it doesn't generate css for every room/every new room created. It checks for userid and apply the icon to the userid. that display in every room/every new room created without generating css for each room and makes the css short.
I've tested it and it works fine.

EDIT: Custom Color works same way as icon.

**Comment by AllianceSky-PS** [comment]
@DeathlyPlays please fix the remaining eslint errors.

**Comment by DeathlyPlays** [comment]
Gotcha

**Comment by DeathlyPlays** [comment]
@Lord-Haji thoughts? Idk CSS design stuff LOL

**Comment by AllianceSky-PS** [comment]
Weird errors -_- https://travis-ci.org/DeathlyPlays/Exiled/builds/321417430?utm_source=github_status&utm_medium=notification @DeathlyPlays

**Comment by AllianceSky-PS** [comment]
@TravisBuddy are you bugged? Test failed but no log smh. 😓😓

**Pull request merged**
