### PR TITLE
Add the slots plugin

### PR DESCRIPTION
**Pull request by AlphaWind**

### CODE REVIEW

**Comment by DeathlyPlays** [comment]
Haha this should fix a load of errors probably missed a few but most kek Ill fix it up

**Comment by DeathlyPlays** [comment]
Already tested also and it worked so that's great

**Comment by DeathlyPlays** [comment]
Nvm I cant add tabs feelsbd bc mobile shit...

**Comment by AlphaWind** [comment]
What's the unmodified loop condition?

**Comment by ghost** [comment]
I have no idea

**Comment by DeathlyPlays** [comment]
Same...

**Comment by DeathlyPlays** [comment]
@HoeenCoder I've never seen this travis error

**Comment by HoeenCoder** [comment]
If you check the context of the error its not hard to see, it dosent like the fact that you didnt edit those variables within the loop, since travis is wrong here you should just disable that check for the loop

**Comment by HoeenCoder** [comment]
or that change :+1:

**Comment by DeathlyPlays** [comment]
:P

**Pull request merged**
