### PR TITLE
add AlfaStorm

### PR DESCRIPTION
**Pull request by ghost**
omg why... just... why... who did this... why did this happen... ughhhh.... this is even worse than hoeenhero, and that's saying something. you know something's wrong when you're crappier than hoeenhero. No offense AlfaStorm but I think someone fucked around with your mon tbh. It needs to be fixed, immediately.

### CODE REVIEW

**Comment by HoeenCoder** [comment]
.

**Comment by DeathlyPlays** [comment]
Its true though @HoeenCoder your mon is so underpowered

**Comment by ghost** [comment]
Lmao @HoeenCoder

**Comment by HoeenCoder** [comment]
TBH I didnt even know my mon was in here, ill buff it up later lol

**Comment by DeathlyPlays** [comment]
Haha you are a dev here so yours was added

**Comment by ghost** [comment]
lmao

**Pull request merged**
